Repository Icinga/icingaweb2-module-cube, pull requests merged in 2022-02, with the labels that each got.

#76 Fix that a `service_description` filter leads to wrong host counts
  library/Cube/Ido/DataView/Hoststatus.php
  library/Cube/Ido/IdoHostStatusCube.php
  library/Cube/Ido/Query/HoststatusQuery.php
Labels: bug, cla/signed

#66 Allow special chars in customvar and make it case natural
  application/forms/DimensionsForm.php
  application/views/helpers/FormSimpleNote.php
  application/views/scripts/cube-index.phtml
  library/Cube/Cube.php
  library/Cube/CubeRenderer.php
  library/Cube/DbCube.php
  library/Cube/Dimension.php
  library/Cube/DimensionParams.php
  library/Cube/Ido/CustomVarDimension.php
  library/Cube/Ido/IdoCube.php
  library/Cube/Ido/IdoHostStatusCube.php
  library/Cube/Ido/IdoHostStatusCubeRenderer.php
  library/Cube/Ido/IdoServiceStatusCube.php
  library/Cube/Ido/IdoStatusCubeRenderer.php
  library/Cube/Web/Controller.php
  library/Cube/Web/Form/CsrfToken.php
  library/Cube/Web/Form/Element/FormElement.php
  library/Cube/Web/Form/Element/SimpleNote.php
  library/Cube/Web/Form/FormLoader.php
  library/Cube/Web/Form/QuickBaseForm.php
  library/Cube/Web/Form/QuickForm.php
  library/Cube/Web/IconHelper.php
  public/css/module.less
Labels: bug, ref/IP, cla/signed

#71 Fix incorrect counts
  library/Cube/Ido/CustomVarDimension.php
  library/Cube/Ido/IdoHostStatusCube.php
  library/Cube/Ido/IdoServiceStatusCube.php
Labels: bug, ref/IP, cla/signed

#79 Update requirements
  module.info
Labels: bug, area/documentation, cla/signed
