Repository Icinga/icingaweb2-module-cube, pull requests merged in 2023-09, with the labels that each got.

#155 Drop IcingaDB `hosts_(unhandled)_unreachable` columns
  library/Cube/CubeRenderer/HostStatusCubeRenderer.php
  library/Cube/IcingaDb/IcingaDbHostStatusCube.php
Labels: bug, cla/signed

#152 Controllers: Remove obsolete tab extension
  library/Cube/Web/Controller.php
  library/Cube/Web/IdoController.php
Labels: enhancement, cla/signed

#153 DimensionParams: Fix `explode(): Passing null to param #2 is deprecated`
  library/Cube/DimensionParams.php
Labels: bug, cla/signed

#154 Controllers: Don't pass `format` param to db query
  library/Cube/Web/Controller.php
  library/Cube/Web/IdoController.php
Labels: bug, cla/signed

#158 Update phpstan baseline config
  phpstan-baseline.neon
Labels: cla/signed

#157 Utilize `ipl\Web\Url::setFilter()` where applicable
  library/Cube/CubeRenderer.php
  library/Cube/ProvidedHook/Cube/IcingaDbActions.php
  library/Cube/Web/Controller.php
  phpstan-baseline.neon
Labels: cla/signed

#159 Release v1.3.2
  doc/02-Installation.md.d/From-Source.md
  module.info
Labels: cla/signed
