Repository Icinga/icingaweb2-module-cube, pull requests merged in 2023-03, with the labels that each got.

#106 IcingaDB cube: Add sort control
  library/Cube/CubeRenderer.php
  library/Cube/CubeRenderer/HostStatusCubeRenderer.php
  library/Cube/CubeRenderer/ServiceStatusCubeRenderer.php
  library/Cube/IcingaDb/IcingaDbCube.php
  library/Cube/Web/Controller.php
  public/css/module.less
Labels: enhancement, cla/signed

#118 Convert params when switching from icingadb to monitoring
  library/Cube/Web/Controller.php
  library/Cube/Web/IdoController.php
Labels: cla/signed

#116 module.less: Fix action link layout
  public/css/module.less
Labels: bug, cla/signed

#108 Test PHP 8.2
  .github/workflows/php.yml
Labels: cla/signed

#119 IcingaDb cube: Respect `(denylist,protect)/variables` restrictions
  library/Cube/IcingaDb/CustomVariableDimension.php
Labels: bug, cla/signed

#124 Monitoring Cube: Pass dimensions param to tabs
  library/Cube/Web/IdoController.php
Labels: cla/signed

#123 Icingadb Cube: Don't pass filter params to tabs
  library/Cube/Web/Controller.php
Labels: cla/signed

#125 Icingadb Cube: (pgsql) Fix/undefined array key error while sorting
  library/Cube/CubeRenderer.php
Labels: cla/signed

#126 IdoController: Remove icingadb control params independently from current active tab
  library/Cube/Web/Controller.php
  library/Cube/Web/IdoController.php
Labels: cla/signed

#122 DimensionsForm: Use ipl-form
  application/forms/DimensionsForm.php
  library/Cube/Web/Controller.php
  library/Cube/Web/IdoController.php
  public/css/module.less
Labels: cla/signed
